import { createClient } from "@supabase/supabase-js";

/**
 * Creates or retrieves a Supabase Client initialized with standard anon public permissions
 * or dynamically authenticated using the Clerk session JWT to respect Row-Level Security policies.
 * 
 * @param clerkToken - The JWT generated by Clerk specifically via the 'supabase' template.
 */
export const createSupabaseClient = (clerkToken?: string) => {
  const supabaseUrl = 
    process.env.NEXT_PUBLIC_SUPABASE_URL || 
    (typeof window !== "undefined" ? (window as any)._env_?.NEXT_PUBLIC_SUPABASE_URL : "") ||
    "";
    
  const supabaseAnonKey = 
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 
    (typeof window !== "undefined" ? (window as any)._env_?.NEXT_PUBLIC_SUPABASE_ANON_KEY : "") ||
    "";

  if (!supabaseUrl || !supabaseAnonKey) {
    console.warn("Supabase clients environment variables are missing! Ensure Supabase URL and Anon Key are set.");
  }

  return createClient(supabaseUrl, supabaseAnonKey, {
    global: {
      headers: clerkToken
        ? {
            Authorization: `Bearer ${clerkToken}`,
          }
        : {},
    },
  });
};
